export const routePaths = {
  home: '/',
  start: '/start',
  chooseOperationType: '/choose-operation-type',
  phoneInput: '/phone-input',
  cardInput: '/card-input',
  printerError: '/printer-error',
  cardError: '/card-error',
  ibanInput: '/iban-input',
  ibanError: '/iban-error',
  textInput: '/text-input',
  cashAcceptance: '/cash-acceptance',
  smsInput: '/sms-input',
  paymentInfo: '/payment-info',
  paymentResult: '/payment-result',
  receipt: '/receipt',
  phoneError: '/phone-error',
  smsError: '/sms-error',
  textError: '/text-error',
  cashError: '/cash-error',
  paymentPurpose: '/payment-purpose',
  purposeError: '/purpose-error',
  utilities: '/utilities',
  utilitiesError: '/utilities-error',
  accountInput: '/account-input',
accountError: '/account-error',
} as const